export const tablesName = [
  "User",
  "Notification",
  "FoodType",
  "Ability",
  "Kennel",
  "Cell",
  "Dog",
  "Round",
  "RoundNote",
  "Pair",
  "Walking",
  "Food",
  "Cleaning",
  "MedicalTreatment",
  "MoveDog",
];

export const columnsName = [
  ["id", "name", "role", "email", "roundResponsible", "group"],
  ["id", "userId", "notification", "date"],
  ["id", "foodType"],
  ["id", "ability"],
  ["id", "kennelName"],
  ["id", "kennelId", "cellName", "cellDescription"],
  [
    "id",
    "userId", //לפי הדרישה צריך לשלוח לפי הטופס שהדס שלחה זה לא נשלח
    "cellId",
    "foodTypeId",
    "abilityId",
    "name",
    "walkingNumber",
    "birthDate",
    "weight",
    "madness", //לפי הדרישה צריך לשלוח לפי הטופס שהדס שלחה זה לא נשלח
    "entryRules",
    "foodAmount",
    "status",
    "fit",
    "rest",
    "nextFeeding",
    "treatment",
    "nextFeedingDate",
  ],
  [
    "id",
    "userId",
    "time",
    "date",
    "number", //לבדוק אם בצבאי הנתון הזה נלקח לדיבי
    "isdone",
    "isactive",
    "reporttime",
    "team",
  ],
  ["id", "note", "team", "number"],
  [
    "id",
    "dogId",
    "userId",
    "startDate",
    "endDate",
    "limitTimeMorning",
    "limitTimeEvening",
  ],
  ["id", "pairId", "isDone", "walkingDate", "isActive"],
  ["id", "pairId", "isDone", "feedingDate", "isActive"],
  [
    "id",
    "pairId",
    "isDone",
    "cleaningDate", //לבדוק אם בצבאי הנתון הזה נלקח לדיבי
    "isActive",
  ],
  ["id", "pairId", "isDone", "medicineRecieved", "isActive"],
  ["id", "fromId", "toId", "sendDate", "dogId", "isActive"],
];
